### ISSUE TITLE
Community happenings feed cross links issue

### ISSUE THREAD

**Issue by pillowtrucker** [neodrama/github-drama#8]
If you link an issue in issue number two then githubs will see the mention in the original issue and come here to continue the flame war because they are deeply and disfunctionally on the spectrum

seems like bad design

**Comment by MSDN-WhiteKnight** [comment]
I could potentially format links as code to prevent Github from parsing them as links and creating cross-references. Currently i don't see it as a big issue, i could just remove off-topic comments when too much of them arrive.

>seems like bad design

There wasn't much design put into it, i've just recreated the "Community happenings feed" from previous incarnation of drama repository.

**Comment by zarlo** [comment]
no

**Comment by mattfbacon** [comment]
> on the spectrum

Unnecessary and disrespectful, funny you say we need a code of conduct
